name: "Generate Changelog"
description: "Fetch merged PRs between two commits, extract ```release-note``` blocks and bucket by /kind labels"
inputs:
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    required: false
    default: ${{ github.token }}
  owner:
    description: "Repo owner/org"
    required: true
  repo:
    description: "Repo name"
    required: true
  start-sha:
    description: "The starting commit SHA (exclusive)"
    required: true
  end-sha:
    description: "The ending commit SHA (inclusive)"
    required: true
  output-path:
    description: "The path to write the changelog to"
    required: false
    default: "CHANGELOG.md"
outputs:
  changelog-path:
    description: "The path to the generated changelog file"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.start-sha }}
    - ${{ inputs.end-sha }}
    - ${{ inputs.output-path }}
