name: "Generate Changelog"
description: "Fetch merged PRs between two commits, extract ```release-note``` blocks and bucket by /kind labels"
inputs:
  github-token:
    description: "GitHub token (usually ${{ secrets.GITHUB_TOKEN }})"
    required: true
  owner:
    description: "Repo owner/org"
    required: true
  repo:
    description: "Repo name"
    required: true
  start-sha:
    description: "The starting commit SHA (exclusive)"
    required: true
  end-sha:
    description: "The ending commit SHA (inclusive)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.start-sha }}
    - ${{ inputs.end-sha }}
